# Generated by Django 3.2.4 on 2022-01-25 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('title_en', models.CharField(max_length=60, null=True)),
                ('title_az', models.CharField(max_length=60, null=True)),
                ('title_ru', models.CharField(max_length=60, null=True)),
                ('cover_image', models.ImageField(upload_to='media/blog_cover_image')),
                ('description', models.CharField(max_length=1000)),
                ('description_en', models.CharField(max_length=1000, null=True)),
                ('description_az', models.CharField(max_length=1000, null=True)),
                ('description_ru', models.CharField(max_length=1000, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default='+994 55 400 16 09')),
            ],
        ),
    ]
