# Generated by Django 3.2.4 on 2021-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_tr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
