# Generated by Django 3.2.4 on 2021-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='IMG.JPG', null=True, upload_to='home_category_images')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_az', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(default='Write your text', max_length=1000)),
                ('description_en', models.CharField(default='Write your text', max_length=1000, null=True)),
                ('description_az', models.CharField(default='Write your text', max_length=1000, null=True)),
                ('description_ru', models.CharField(default='Write your text', max_length=1000, null=True)),
                ('cover_image', models.ImageField(upload_to='product_cover_image')),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ManyToManyField(blank=True, db_index=True, default='Something', related_name='product_categories', to='product.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
