# Generated by Django 3.2.4 on 2021-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(blank=True, db_index=True, default='Something', related_name='product_categories', to='product.Category'),
        ),
    ]
