# Generated by Django 3.2.4 on 2021-08-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210829_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='category',
        ),
    ]
