# Generated by Django 3.2.4 on 2021-09-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210907_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_tr',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_tr',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_tr',
            new_name='title_ru',
        ),
    ]
