# Generated by Django 3.2.4 on 2021-09-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210907_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
    ]
