# Generated by Django 3.2.4 on 2021-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_az', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(default='Write the text', max_length=1000)),
                ('description_en', models.CharField(default='Write the text', max_length=1000, null=True)),
                ('description_az', models.CharField(default='Write the text', max_length=1000, null=True)),
                ('description_ru', models.CharField(default='Write the text', max_length=1000, null=True)),
                ('cover_image', models.ImageField(upload_to='media/services_image')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
