# Generated by Django 3.2.4 on 2021-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_az',
            field=models.CharField(default='Write the text', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.CharField(default='Write the text', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_tr',
            field=models.CharField(default='Write the text', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
